
import React, { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { useAuth } from '@/hooks/useAuth';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';

export default function TelegramLink() {
  const [location, setLocation] = useLocation();
  const searchParams = new URLSearchParams(window.location.search);
  const { user, isAuthenticated, login } = useAuth();
  const { toast } = useToast();
  const [isLinking, setIsLinking] = useState(false);
  const [linkStatus, setLinkStatus] = useState<'pending' | 'success' | 'error'>('pending');
  const [errorMessage, setErrorMessage] = useState('');
  const [awaitingAuth, setAwaitingAuth] = useState(false);
  const [authCheckComplete, setAuthCheckComplete] = useState(false);

  useEffect(() => {
    const autoVerify = async () => {
      const token = searchParams.get('token');

      // If token is in sessionStorage but not URL, restore it (happens after auth redirect)
      const storedToken = sessionStorage.getItem('telegram_token');
      const finalToken = token || storedToken;

      if (!finalToken) {
        setLinkStatus('error');
        setErrorMessage('Invalid link. Please use /start in Telegram to get a new link.');
        return;
      }

      if (!authCheckComplete) {
        setTimeout(() => setAuthCheckComplete(true), 300);
        return;
      }

      if (isAuthenticated) {
        await handleVerify(finalToken);
        // Clear stored token after verify attempt
        sessionStorage.removeItem('telegram_token');
      }
    };

    autoVerify();
  }, [user, isAuthenticated, authCheckComplete, toast]);

  const handleVerify = async (token?: string | null) => {
    const t = token ?? searchParams.get('token');
    if (!t) {
      setLinkStatus('error');
      setErrorMessage('Invalid link token');
      return;
    }

    setIsLinking(true);
    try {
      const response = await apiRequest(`/api/telegram/verify-link?token=${t}`, { method: 'GET' });

      if (response.success) {
        setLinkStatus('success');
        toast({ title: 'Account Linked!', description: 'Your Telegram account has been successfully linked.' });

        // Attempt to open Telegram to show the bot confirmation (deep link or web)
        try {
          if (telegramDeepLink) {
            window.open(telegramDeepLink, '_blank');
          } else {
            window.open(telegramWebUrl, '_blank');
          }
        } catch (_) {}

        setTimeout(() => setLocation('/profile'), 2000);
      } else {
        setLinkStatus('error');
        setErrorMessage(response.message || 'Failed to link account');
        toast({ title: 'Link Failed', description: response.message, variant: 'destructive' });
      }
    } catch (err) {
      setLinkStatus('error');
      setErrorMessage('An error occurred. Please try again.');
      toast({ title: 'Error', description: 'Failed to link Telegram account', variant: 'destructive' });
    } finally {
      setIsLinking(false);
    }
  };

  const botUsername = (import.meta as any).env?.VITE_TELEGRAM_BOT_USERNAME || '';
  const telegramWebUrl = botUsername ? `https://t.me/${botUsername}` : 'https://t.me/';
  const telegramDeepLink = botUsername ? `tg://resolve?domain=${botUsername}` : telegramWebUrl;

  return (
    <Dialog open onOpenChange={() => setLocation('/') }>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="text-center">Link your Telegram account</DialogTitle>
          <DialogDescription className="text-center">Use this dialog to connect your Telegram account to Bantah. Follow the instructions below.</DialogDescription>
          <div className="text-center mt-2 text-sm text-slate-600">
            <p>
              This link was generated by <strong>@{botUsername || 'the bot'}</strong>. Signing in will link the Telegram account you used to open this link with your Bantah web account. If you don't have an account, signing up will create one and then link it.
            </p>
            <p className="mt-1">
              <a href={telegramWebUrl} target="_blank" rel="noreferrer" className="text-primary underline">Open in Telegram</a> to re-check the bot message.
            </p>
          </div>
        </DialogHeader>

        <div className="mt-4">
          <Card className="w-full">
            <CardHeader>
              <CardTitle className="text-center">
                {linkStatus === 'pending' && '🔗 Linking Telegram Account...'}
                {linkStatus === 'success' && '✅ Account Linked!'}
                {linkStatus === 'error' && '❌ Link Failed'}
              </CardTitle>
            </CardHeader>
            <CardContent className="text-center">
              {isLinking && (
                <div className="space-y-4">
                  <div className="w-16 h-16 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto"></div>
                  <p className="text-slate-600 dark:text-slate-400">Linking your Telegram account...</p>
                </div>
              )}

              {linkStatus === 'success' && (
                <div className="space-y-4">
                  <div className="text-6xl">🎉</div>
                  <p className="text-lg font-semibold text-slate-900 dark:text-slate-100">Success!</p>
                  <p className="text-slate-600 dark:text-slate-400">Your Telegram account is now linked to Bantah.</p>
                  <p className="text-sm text-slate-500">Redirecting to your profile...</p>
                  <div className="mt-2">
                    <a href={telegramWebUrl} target="_blank" rel="noreferrer">
                      <Button className="w-full">Open Telegram</Button>
                    </a>
                    <p className="text-xs text-slate-500 mt-2">Or open the Telegram app to continue using the bot.</p>
                  </div>
                </div>
              )}

              {linkStatus === 'error' && (
                <div className="space-y-4">
                  <div className="text-6xl">⚠️</div>
                  <p className="text-lg font-semibold text-red-600 dark:text-red-400">Link Failed</p>
                  <p className="text-slate-600 dark:text-slate-400">{errorMessage}</p>
                  <div className="space-y-2">
                    <Button onClick={() => setLocation('/profile')} className="w-full">Go to Profile</Button>
                    <p className="text-xs text-slate-500">Open Telegram and use /start to get a new link</p>
                  </div>
                </div>
              )}

              {/* Action area for logged-in vs logged-out */}
              {!isLinking && linkStatus === 'pending' && (
                <div className="mt-4 space-y-2">
                      {isAuthenticated ? (
                    <Button className="w-full" onClick={() => handleVerify()} disabled={isLinking || awaitingAuth}>Link my account now</Button>
                  ) : (
                    <>
                      <p className="text-sm text-slate-600">You need to sign in to link your account.</p>
                      <div className="space-y-2">
                        <Button className="w-full" onClick={async () => {
                          const token = searchParams.get('token');
                          // Save token to sessionStorage before triggering auth
                          if (token) {
                            try { sessionStorage.setItem('telegram_token', token); } catch (_) {}
                          }

                          // Show standby state so the user knows to complete the Privy flow
                          setAwaitingAuth(true);

                          // Trigger Privy login flow. Fallback to navigating to home if login isn't available.
                          try {
                            if (typeof login === 'function') {
                              await login();
                            } else {
                              setLocation(`/?telegram_token=${token}`);
                            }
                          } catch (err) {
                            // If login fails or isn't available, navigate to home with token in query
                            setLocation(`/?telegram_token=${token}`);
                          } finally {
                            // We don't immediately clear awaitingAuth here because the app may redirect.
                            // When the user returns, `autoVerify` will clear sessionStorage after verification.
                          }
                        }} disabled={awaitingAuth}>
                          {awaitingAuth ? 'Waiting for sign in...' : 'Sign in / Sign up'}
                        </Button>
                        <p className="text-xs text-slate-500">A Privy window will open — complete sign in to link your Telegram account.</p>
                      </div>
                    </>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </DialogContent>
    </Dialog>
  );
}
